// Regras globais de composição — definidas aqui uma única vez e importadas por
// buildImagePrompt (api.ts) e buildPostUnicoPrompt (postUnico.ts).
// Garante consistência entre os dois sistemas e evita versões divergentes do mesmo bloco.

export const DEVICE_RULE = `⚠ DISPOSITIVOS DIGITAIS: notebook, laptop, tablet, iPad, celular, iPhone, monitor e outros dispositivos são PERMITIDOS em qualquer posição natural — abertos, em uso, na mão, apoiados, inclinados, sobre a mesa. NÃO forçar dispositivo fechado. PROIBIDO APENAS: (1) conteúdo visível na tela frontal — gráfico, dashboard, imagem, interface, app, texto legível ou qualquer elemento visual — a tela deve estar escura ou neutra, mas o dispositivo PODE estar aberto e em posição de uso; (2) imagem, logo ou adesivo na carcaça ou tampa traseira — devem ser lisos e sem estampa. MÁXIMO 1 DISPOSITIVO por cena. NEGATIVE: no visible screen content, no charts, no dashboard, no UI, no readable text on screen, no images or graphics on device casing or back cover, no duplicated devices, screen must be dark or neutral (no content visible), casing must be plain.`;

export const AMBIENTES_RULE = `⚠ AMBIENTES VISUAIS: PROIBIDO paredes de concreto aparente, galpões industriais, estruturas arquitetônicas frias, corredores vazios como elemento dominante ou fundo para tipografia. Use fundos coloridos, texturas orgânicas, desfoque, gradiente ou fotografia quente. PROIBIDO TAMBÉM: formas geométricas abstratas flutuando (círculos, esferas, polígonos, espirais) sem propósito narrativo. A composição deve ter TEMA CONCRETO — humano, objeto real, natureza, tipografia ou cenário com sentido.`;

export const HUMANIZACAO_RULE = `⚠ HUMANIZAÇÃO: imagens devem parecer humanas, autênticas e reais. PROIBIDO inserir vasos, plantas ornamentais, folhas ou flores apenas para preencher cantos — todo elemento deve contribuir para a mensagem.`;

export const FORBIDDEN_MOOD_WORDS = `PALAVRAS PROIBIDAS NA IMAGEM: NUNCA escreva, desenhe ou renderize como texto/lettering/título/etiqueta, em nenhum lugar da peça, as palavras CLAREZA, IMPACTO, INSTANTE, FRAGMENTO, DESVIO, SILÊNCIO, MOOD, OP-01, OP-02, OP-03, OP-04, OP-05, OP-06 — são códigos internos do sistema e nunca devem aparecer na arte final.`;
