/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ExclusaoDeDadosRouteImport } from './routes/exclusao-de-dados'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AppRouteImport } from './routes/app'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsVoiceRouteImport } from './routes/api/tts-voice'
import { Route as ApiSupabasePdfRouteImport } from './routes/api/supabase-pdf'
import { Route as ApiSuggestKeyinfoRouteImport } from './routes/api/suggest-keyinfo'
import { Route as ApiRegenerateBlockRouteImport } from './routes/api/regenerate-block'
import { Route as ApiJudgeLogoRouteImport } from './routes/api/judge-logo'
import { Route as ApiJudgeContentRouteImport } from './routes/api/judge-content'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGeneratePuCopyRouteImport } from './routes/api/generate-pu-copy'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGenerateContentRouteImport } from './routes/api/generate-content'
import { Route as ApiGenerateCaptionRouteImport } from './routes/api/generate-caption'
import { Route as ApiFalStatusRouteImport } from './routes/api/fal-status'
import { Route as ApiDeleteVoiceRouteImport } from './routes/api/delete-voice'
import { Route as ApiCorrectTextRouteImport } from './routes/api/correct-text'
import { Route as ApiConfirmVoiceRouteImport } from './routes/api/confirm-voice'
import { Route as ApiCloneVoiceRouteImport } from './routes/api/clone-voice'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth/meta/callback'
import { Route as ApiPublicExpireGenerationsRouteImport } from './routes/api/public/expire-generations'
import { Route as ApiMetaTestPublishRouteImport } from './routes/api/meta/test-publish'
import { Route as ApiMetaStatusRouteImport } from './routes/api/meta/status'
import { Route as ApiMetaPublishInstagramRouteImport } from './routes/api/meta/publish-instagram'
import { Route as ApiMetaPublishFacebookRouteImport } from './routes/api/meta/publish-facebook'
import { Route as ApiMetaDisconnectRouteImport } from './routes/api/meta/disconnect'
import { Route as ApiMetaDebugAccountsRouteImport } from './routes/api/meta/debug-accounts'
import { Route as ApiMetaAutopostInstagramRouteImport } from './routes/api/meta/autopost-instagram'
import { Route as ApiMetaAutopostFacebookRouteImport } from './routes/api/meta/autopost-facebook'
import { Route as ApiMetaAuthUrlRouteImport } from './routes/api/meta/auth-url'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusaoDeDadosRoute = ExclusaoDeDadosRouteImport.update({
  id: '/exclusao-de-dados',
  path: '/exclusao-de-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsVoiceRoute = ApiTtsVoiceRouteImport.update({
  id: '/api/tts-voice',
  path: '/api/tts-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabasePdfRoute = ApiSupabasePdfRouteImport.update({
  id: '/api/supabase-pdf',
  path: '/api/supabase-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestKeyinfoRoute = ApiSuggestKeyinfoRouteImport.update({
  id: '/api/suggest-keyinfo',
  path: '/api/suggest-keyinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegenerateBlockRoute = ApiRegenerateBlockRouteImport.update({
  id: '/api/regenerate-block',
  path: '/api/regenerate-block',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgeLogoRoute = ApiJudgeLogoRouteImport.update({
  id: '/api/judge-logo',
  path: '/api/judge-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgeContentRoute = ApiJudgeContentRouteImport.update({
  id: '/api/judge-content',
  path: '/api/judge-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePuCopyRoute = ApiGeneratePuCopyRouteImport.update({
  id: '/api/generate-pu-copy',
  path: '/api/generate-pu-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateContentRoute = ApiGenerateContentRouteImport.update({
  id: '/api/generate-content',
  path: '/api/generate-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCaptionRoute = ApiGenerateCaptionRouteImport.update({
  id: '/api/generate-caption',
  path: '/api/generate-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFalStatusRoute = ApiFalStatusRouteImport.update({
  id: '/api/fal-status',
  path: '/api/fal-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteVoiceRoute = ApiDeleteVoiceRouteImport.update({
  id: '/api/delete-voice',
  path: '/api/delete-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCorrectTextRoute = ApiCorrectTextRouteImport.update({
  id: '/api/correct-text',
  path: '/api/correct-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmVoiceRoute = ApiConfirmVoiceRouteImport.update({
  id: '/api/confirm-voice',
  path: '/api/confirm-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloneVoiceRoute = ApiCloneVoiceRouteImport.update({
  id: '/api/clone-voice',
  path: '/api/clone-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/auth/meta/callback',
  path: '/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpireGenerationsRoute =
  ApiPublicExpireGenerationsRouteImport.update({
    id: '/api/public/expire-generations',
    path: '/api/public/expire-generations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaTestPublishRoute = ApiMetaTestPublishRouteImport.update({
  id: '/api/meta/test-publish',
  path: '/api/meta/test-publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaStatusRoute = ApiMetaStatusRouteImport.update({
  id: '/api/meta/status',
  path: '/api/meta/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaPublishInstagramRoute = ApiMetaPublishInstagramRouteImport.update({
  id: '/api/meta/publish-instagram',
  path: '/api/meta/publish-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaPublishFacebookRoute = ApiMetaPublishFacebookRouteImport.update({
  id: '/api/meta/publish-facebook',
  path: '/api/meta/publish-facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaDisconnectRoute = ApiMetaDisconnectRouteImport.update({
  id: '/api/meta/disconnect',
  path: '/api/meta/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaDebugAccountsRoute = ApiMetaDebugAccountsRouteImport.update({
  id: '/api/meta/debug-accounts',
  path: '/api/meta/debug-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaAutopostInstagramRoute =
  ApiMetaAutopostInstagramRouteImport.update({
    id: '/api/meta/autopost-instagram',
    path: '/api/meta/autopost-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaAutopostFacebookRoute = ApiMetaAutopostFacebookRouteImport.update({
  id: '/api/meta/autopost-facebook',
  path: '/api/meta/autopost-facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaAuthUrlRoute = ApiMetaAuthUrlRouteImport.update({
  id: '/api/meta/auth-url',
  path: '/api/meta/auth-url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/correct-text': typeof ApiCorrectTextRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/judge-content': typeof ApiJudgeContentRoute
  '/api/judge-logo': typeof ApiJudgeLogoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/meta/auth-url': typeof ApiMetaAuthUrlRoute
  '/api/meta/autopost-facebook': typeof ApiMetaAutopostFacebookRoute
  '/api/meta/autopost-instagram': typeof ApiMetaAutopostInstagramRoute
  '/api/meta/debug-accounts': typeof ApiMetaDebugAccountsRoute
  '/api/meta/disconnect': typeof ApiMetaDisconnectRoute
  '/api/meta/publish-facebook': typeof ApiMetaPublishFacebookRoute
  '/api/meta/publish-instagram': typeof ApiMetaPublishInstagramRoute
  '/api/meta/status': typeof ApiMetaStatusRoute
  '/api/meta/test-publish': typeof ApiMetaTestPublishRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/correct-text': typeof ApiCorrectTextRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/judge-content': typeof ApiJudgeContentRoute
  '/api/judge-logo': typeof ApiJudgeLogoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/meta/auth-url': typeof ApiMetaAuthUrlRoute
  '/api/meta/autopost-facebook': typeof ApiMetaAutopostFacebookRoute
  '/api/meta/autopost-instagram': typeof ApiMetaAutopostInstagramRoute
  '/api/meta/debug-accounts': typeof ApiMetaDebugAccountsRoute
  '/api/meta/disconnect': typeof ApiMetaDisconnectRoute
  '/api/meta/publish-facebook': typeof ApiMetaPublishFacebookRoute
  '/api/meta/publish-instagram': typeof ApiMetaPublishInstagramRoute
  '/api/meta/status': typeof ApiMetaStatusRoute
  '/api/meta/test-publish': typeof ApiMetaTestPublishRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exclusao-de-dados': typeof ExclusaoDeDadosRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/correct-text': typeof ApiCorrectTextRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/judge-content': typeof ApiJudgeContentRoute
  '/api/judge-logo': typeof ApiJudgeLogoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/meta/auth-url': typeof ApiMetaAuthUrlRoute
  '/api/meta/autopost-facebook': typeof ApiMetaAutopostFacebookRoute
  '/api/meta/autopost-instagram': typeof ApiMetaAutopostInstagramRoute
  '/api/meta/debug-accounts': typeof ApiMetaDebugAccountsRoute
  '/api/meta/disconnect': typeof ApiMetaDisconnectRoute
  '/api/meta/publish-facebook': typeof ApiMetaPublishFacebookRoute
  '/api/meta/publish-instagram': typeof ApiMetaPublishInstagramRoute
  '/api/meta/status': typeof ApiMetaStatusRoute
  '/api/meta/test-publish': typeof ApiMetaTestPublishRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/exclusao-de-dados'
    | '/historico'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/correct-text'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/judge-content'
    | '/api/judge-logo'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/meta/auth-url'
    | '/api/meta/autopost-facebook'
    | '/api/meta/autopost-instagram'
    | '/api/meta/debug-accounts'
    | '/api/meta/disconnect'
    | '/api/meta/publish-facebook'
    | '/api/meta/publish-instagram'
    | '/api/meta/status'
    | '/api/meta/test-publish'
    | '/api/public/expire-generations'
    | '/auth/meta/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/exclusao-de-dados'
    | '/historico'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/correct-text'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/judge-content'
    | '/api/judge-logo'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/meta/auth-url'
    | '/api/meta/autopost-facebook'
    | '/api/meta/autopost-instagram'
    | '/api/meta/debug-accounts'
    | '/api/meta/disconnect'
    | '/api/meta/publish-facebook'
    | '/api/meta/publish-instagram'
    | '/api/meta/status'
    | '/api/meta/test-publish'
    | '/api/public/expire-generations'
    | '/auth/meta/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/exclusao-de-dados'
    | '/historico'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/termos'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/correct-text'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/judge-content'
    | '/api/judge-logo'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/meta/auth-url'
    | '/api/meta/autopost-facebook'
    | '/api/meta/autopost-instagram'
    | '/api/meta/debug-accounts'
    | '/api/meta/disconnect'
    | '/api/meta/publish-facebook'
    | '/api/meta/publish-instagram'
    | '/api/meta/status'
    | '/api/meta/test-publish'
    | '/api/public/expire-generations'
    | '/auth/meta/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjustesRoute: typeof AjustesRoute
  AppRoute: typeof AppRoute
  ContaRoute: typeof ContaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  ExclusaoDeDadosRoute: typeof ExclusaoDeDadosRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiCloneVoiceRoute: typeof ApiCloneVoiceRoute
  ApiConfirmVoiceRoute: typeof ApiConfirmVoiceRoute
  ApiCorrectTextRoute: typeof ApiCorrectTextRoute
  ApiDeleteVoiceRoute: typeof ApiDeleteVoiceRoute
  ApiFalStatusRoute: typeof ApiFalStatusRoute
  ApiGenerateCaptionRoute: typeof ApiGenerateCaptionRoute
  ApiGenerateContentRoute: typeof ApiGenerateContentRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGeneratePuCopyRoute: typeof ApiGeneratePuCopyRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiJudgeContentRoute: typeof ApiJudgeContentRoute
  ApiJudgeLogoRoute: typeof ApiJudgeLogoRoute
  ApiRegenerateBlockRoute: typeof ApiRegenerateBlockRoute
  ApiSuggestKeyinfoRoute: typeof ApiSuggestKeyinfoRoute
  ApiSupabasePdfRoute: typeof ApiSupabasePdfRoute
  ApiTtsVoiceRoute: typeof ApiTtsVoiceRoute
  ApiMetaAuthUrlRoute: typeof ApiMetaAuthUrlRoute
  ApiMetaAutopostFacebookRoute: typeof ApiMetaAutopostFacebookRoute
  ApiMetaAutopostInstagramRoute: typeof ApiMetaAutopostInstagramRoute
  ApiMetaDebugAccountsRoute: typeof ApiMetaDebugAccountsRoute
  ApiMetaDisconnectRoute: typeof ApiMetaDisconnectRoute
  ApiMetaPublishFacebookRoute: typeof ApiMetaPublishFacebookRoute
  ApiMetaPublishInstagramRoute: typeof ApiMetaPublishInstagramRoute
  ApiMetaStatusRoute: typeof ApiMetaStatusRoute
  ApiMetaTestPublishRoute: typeof ApiMetaTestPublishRoute
  ApiPublicExpireGenerationsRoute: typeof ApiPublicExpireGenerationsRoute
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusao-de-dados': {
      id: '/exclusao-de-dados'
      path: '/exclusao-de-dados'
      fullPath: '/exclusao-de-dados'
      preLoaderRoute: typeof ExclusaoDeDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-voice': {
      id: '/api/tts-voice'
      path: '/api/tts-voice'
      fullPath: '/api/tts-voice'
      preLoaderRoute: typeof ApiTtsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase-pdf': {
      id: '/api/supabase-pdf'
      path: '/api/supabase-pdf'
      fullPath: '/api/supabase-pdf'
      preLoaderRoute: typeof ApiSupabasePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-keyinfo': {
      id: '/api/suggest-keyinfo'
      path: '/api/suggest-keyinfo'
      fullPath: '/api/suggest-keyinfo'
      preLoaderRoute: typeof ApiSuggestKeyinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regenerate-block': {
      id: '/api/regenerate-block'
      path: '/api/regenerate-block'
      fullPath: '/api/regenerate-block'
      preLoaderRoute: typeof ApiRegenerateBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judge-content': {
      id: '/api/judge-content'
      path: '/api/judge-content'
      fullPath: '/api/judge-content'
      preLoaderRoute: typeof ApiJudgeContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judge-logo': {
      id: '/api/judge-logo'
      path: '/api/judge-logo'
      fullPath: '/api/judge-logo'
      preLoaderRoute: typeof ApiJudgeLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-pu-copy': {
      id: '/api/generate-pu-copy'
      path: '/api/generate-pu-copy'
      fullPath: '/api/generate-pu-copy'
      preLoaderRoute: typeof ApiGeneratePuCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-content': {
      id: '/api/generate-content'
      path: '/api/generate-content'
      fullPath: '/api/generate-content'
      preLoaderRoute: typeof ApiGenerateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-caption': {
      id: '/api/generate-caption'
      path: '/api/generate-caption'
      fullPath: '/api/generate-caption'
      preLoaderRoute: typeof ApiGenerateCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fal-status': {
      id: '/api/fal-status'
      path: '/api/fal-status'
      fullPath: '/api/fal-status'
      preLoaderRoute: typeof ApiFalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-voice': {
      id: '/api/delete-voice'
      path: '/api/delete-voice'
      fullPath: '/api/delete-voice'
      preLoaderRoute: typeof ApiDeleteVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/correct-text': {
      id: '/api/correct-text'
      path: '/api/correct-text'
      fullPath: '/api/correct-text'
      preLoaderRoute: typeof ApiCorrectTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm-voice': {
      id: '/api/confirm-voice'
      path: '/api/confirm-voice'
      fullPath: '/api/confirm-voice'
      preLoaderRoute: typeof ApiConfirmVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clone-voice': {
      id: '/api/clone-voice'
      path: '/api/clone-voice'
      fullPath: '/api/clone-voice'
      preLoaderRoute: typeof ApiCloneVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/auth/meta/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-generations': {
      id: '/api/public/expire-generations'
      path: '/api/public/expire-generations'
      fullPath: '/api/public/expire-generations'
      preLoaderRoute: typeof ApiPublicExpireGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/test-publish': {
      id: '/api/meta/test-publish'
      path: '/api/meta/test-publish'
      fullPath: '/api/meta/test-publish'
      preLoaderRoute: typeof ApiMetaTestPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/status': {
      id: '/api/meta/status'
      path: '/api/meta/status'
      fullPath: '/api/meta/status'
      preLoaderRoute: typeof ApiMetaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/publish-instagram': {
      id: '/api/meta/publish-instagram'
      path: '/api/meta/publish-instagram'
      fullPath: '/api/meta/publish-instagram'
      preLoaderRoute: typeof ApiMetaPublishInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/publish-facebook': {
      id: '/api/meta/publish-facebook'
      path: '/api/meta/publish-facebook'
      fullPath: '/api/meta/publish-facebook'
      preLoaderRoute: typeof ApiMetaPublishFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/disconnect': {
      id: '/api/meta/disconnect'
      path: '/api/meta/disconnect'
      fullPath: '/api/meta/disconnect'
      preLoaderRoute: typeof ApiMetaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/debug-accounts': {
      id: '/api/meta/debug-accounts'
      path: '/api/meta/debug-accounts'
      fullPath: '/api/meta/debug-accounts'
      preLoaderRoute: typeof ApiMetaDebugAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/autopost-instagram': {
      id: '/api/meta/autopost-instagram'
      path: '/api/meta/autopost-instagram'
      fullPath: '/api/meta/autopost-instagram'
      preLoaderRoute: typeof ApiMetaAutopostInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/autopost-facebook': {
      id: '/api/meta/autopost-facebook'
      path: '/api/meta/autopost-facebook'
      fullPath: '/api/meta/autopost-facebook'
      preLoaderRoute: typeof ApiMetaAutopostFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/auth-url': {
      id: '/api/meta/auth-url'
      path: '/api/meta/auth-url'
      fullPath: '/api/meta/auth-url'
      preLoaderRoute: typeof ApiMetaAuthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjustesRoute: AjustesRoute,
  AppRoute: AppRoute,
  ContaRoute: ContaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  ExclusaoDeDadosRoute: ExclusaoDeDadosRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiCloneVoiceRoute: ApiCloneVoiceRoute,
  ApiConfirmVoiceRoute: ApiConfirmVoiceRoute,
  ApiCorrectTextRoute: ApiCorrectTextRoute,
  ApiDeleteVoiceRoute: ApiDeleteVoiceRoute,
  ApiFalStatusRoute: ApiFalStatusRoute,
  ApiGenerateCaptionRoute: ApiGenerateCaptionRoute,
  ApiGenerateContentRoute: ApiGenerateContentRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGeneratePuCopyRoute: ApiGeneratePuCopyRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiJudgeContentRoute: ApiJudgeContentRoute,
  ApiJudgeLogoRoute: ApiJudgeLogoRoute,
  ApiRegenerateBlockRoute: ApiRegenerateBlockRoute,
  ApiSuggestKeyinfoRoute: ApiSuggestKeyinfoRoute,
  ApiSupabasePdfRoute: ApiSupabasePdfRoute,
  ApiTtsVoiceRoute: ApiTtsVoiceRoute,
  ApiMetaAuthUrlRoute: ApiMetaAuthUrlRoute,
  ApiMetaAutopostFacebookRoute: ApiMetaAutopostFacebookRoute,
  ApiMetaAutopostInstagramRoute: ApiMetaAutopostInstagramRoute,
  ApiMetaDebugAccountsRoute: ApiMetaDebugAccountsRoute,
  ApiMetaDisconnectRoute: ApiMetaDisconnectRoute,
  ApiMetaPublishFacebookRoute: ApiMetaPublishFacebookRoute,
  ApiMetaPublishInstagramRoute: ApiMetaPublishInstagramRoute,
  ApiMetaStatusRoute: ApiMetaStatusRoute,
  ApiMetaTestPublishRoute: ApiMetaTestPublishRoute,
  ApiPublicExpireGenerationsRoute: ApiPublicExpireGenerationsRoute,
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
