/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as AppRouteImport } from './routes/app'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsVoiceRouteImport } from './routes/api/tts-voice'
import { Route as ApiSupabasePdfRouteImport } from './routes/api/supabase-pdf'
import { Route as ApiSuggestKeyinfoRouteImport } from './routes/api/suggest-keyinfo'
import { Route as ApiRegenerateBlockRouteImport } from './routes/api/regenerate-block'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGeneratePuCopyRouteImport } from './routes/api/generate-pu-copy'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGenerateContentRouteImport } from './routes/api/generate-content'
import { Route as ApiGenerateCaptionRouteImport } from './routes/api/generate-caption'
import { Route as ApiFalStatusRouteImport } from './routes/api/fal-status'
import { Route as ApiDeleteVoiceRouteImport } from './routes/api/delete-voice'
import { Route as ApiConfirmVoiceRouteImport } from './routes/api/confirm-voice'
import { Route as ApiCloneVoiceRouteImport } from './routes/api/clone-voice'
import { Route as ApiPublicExpireGenerationsRouteImport } from './routes/api/public/expire-generations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsVoiceRoute = ApiTtsVoiceRouteImport.update({
  id: '/api/tts-voice',
  path: '/api/tts-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabasePdfRoute = ApiSupabasePdfRouteImport.update({
  id: '/api/supabase-pdf',
  path: '/api/supabase-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestKeyinfoRoute = ApiSuggestKeyinfoRouteImport.update({
  id: '/api/suggest-keyinfo',
  path: '/api/suggest-keyinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegenerateBlockRoute = ApiRegenerateBlockRouteImport.update({
  id: '/api/regenerate-block',
  path: '/api/regenerate-block',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePuCopyRoute = ApiGeneratePuCopyRouteImport.update({
  id: '/api/generate-pu-copy',
  path: '/api/generate-pu-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateContentRoute = ApiGenerateContentRouteImport.update({
  id: '/api/generate-content',
  path: '/api/generate-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCaptionRoute = ApiGenerateCaptionRouteImport.update({
  id: '/api/generate-caption',
  path: '/api/generate-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFalStatusRoute = ApiFalStatusRouteImport.update({
  id: '/api/fal-status',
  path: '/api/fal-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteVoiceRoute = ApiDeleteVoiceRouteImport.update({
  id: '/api/delete-voice',
  path: '/api/delete-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfirmVoiceRoute = ApiConfirmVoiceRouteImport.update({
  id: '/api/confirm-voice',
  path: '/api/confirm-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloneVoiceRoute = ApiCloneVoiceRouteImport.update({
  id: '/api/clone-voice',
  path: '/api/clone-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExpireGenerationsRoute =
  ApiPublicExpireGenerationsRouteImport.update({
    id: '/api/public/expire-generations',
    path: '/api/public/expire-generations',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajustes': typeof AjustesRoute
  '/app': typeof AppRoute
  '/conta': typeof ContaRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/clone-voice': typeof ApiCloneVoiceRoute
  '/api/confirm-voice': typeof ApiConfirmVoiceRoute
  '/api/delete-voice': typeof ApiDeleteVoiceRoute
  '/api/fal-status': typeof ApiFalStatusRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-pu-copy': typeof ApiGeneratePuCopyRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/regenerate-block': typeof ApiRegenerateBlockRoute
  '/api/suggest-keyinfo': typeof ApiSuggestKeyinfoRoute
  '/api/supabase-pdf': typeof ApiSupabasePdfRoute
  '/api/tts-voice': typeof ApiTtsVoiceRoute
  '/api/public/expire-generations': typeof ApiPublicExpireGenerationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/public/expire-generations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/public/expire-generations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajustes'
    | '/app'
    | '/conta'
    | '/esqueci-senha'
    | '/historico'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/clone-voice'
    | '/api/confirm-voice'
    | '/api/delete-voice'
    | '/api/fal-status'
    | '/api/generate-caption'
    | '/api/generate-content'
    | '/api/generate-image'
    | '/api/generate-pu-copy'
    | '/api/generate-video'
    | '/api/regenerate-block'
    | '/api/suggest-keyinfo'
    | '/api/supabase-pdf'
    | '/api/tts-voice'
    | '/api/public/expire-generations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjustesRoute: typeof AjustesRoute
  AppRoute: typeof AppRoute
  ContaRoute: typeof ContaRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiCloneVoiceRoute: typeof ApiCloneVoiceRoute
  ApiConfirmVoiceRoute: typeof ApiConfirmVoiceRoute
  ApiDeleteVoiceRoute: typeof ApiDeleteVoiceRoute
  ApiFalStatusRoute: typeof ApiFalStatusRoute
  ApiGenerateCaptionRoute: typeof ApiGenerateCaptionRoute
  ApiGenerateContentRoute: typeof ApiGenerateContentRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGeneratePuCopyRoute: typeof ApiGeneratePuCopyRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiRegenerateBlockRoute: typeof ApiRegenerateBlockRoute
  ApiSuggestKeyinfoRoute: typeof ApiSuggestKeyinfoRoute
  ApiSupabasePdfRoute: typeof ApiSupabasePdfRoute
  ApiTtsVoiceRoute: typeof ApiTtsVoiceRoute
  ApiPublicExpireGenerationsRoute: typeof ApiPublicExpireGenerationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-voice': {
      id: '/api/tts-voice'
      path: '/api/tts-voice'
      fullPath: '/api/tts-voice'
      preLoaderRoute: typeof ApiTtsVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase-pdf': {
      id: '/api/supabase-pdf'
      path: '/api/supabase-pdf'
      fullPath: '/api/supabase-pdf'
      preLoaderRoute: typeof ApiSupabasePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest-keyinfo': {
      id: '/api/suggest-keyinfo'
      path: '/api/suggest-keyinfo'
      fullPath: '/api/suggest-keyinfo'
      preLoaderRoute: typeof ApiSuggestKeyinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regenerate-block': {
      id: '/api/regenerate-block'
      path: '/api/regenerate-block'
      fullPath: '/api/regenerate-block'
      preLoaderRoute: typeof ApiRegenerateBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-pu-copy': {
      id: '/api/generate-pu-copy'
      path: '/api/generate-pu-copy'
      fullPath: '/api/generate-pu-copy'
      preLoaderRoute: typeof ApiGeneratePuCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-content': {
      id: '/api/generate-content'
      path: '/api/generate-content'
      fullPath: '/api/generate-content'
      preLoaderRoute: typeof ApiGenerateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-caption': {
      id: '/api/generate-caption'
      path: '/api/generate-caption'
      fullPath: '/api/generate-caption'
      preLoaderRoute: typeof ApiGenerateCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fal-status': {
      id: '/api/fal-status'
      path: '/api/fal-status'
      fullPath: '/api/fal-status'
      preLoaderRoute: typeof ApiFalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-voice': {
      id: '/api/delete-voice'
      path: '/api/delete-voice'
      fullPath: '/api/delete-voice'
      preLoaderRoute: typeof ApiDeleteVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/confirm-voice': {
      id: '/api/confirm-voice'
      path: '/api/confirm-voice'
      fullPath: '/api/confirm-voice'
      preLoaderRoute: typeof ApiConfirmVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clone-voice': {
      id: '/api/clone-voice'
      path: '/api/clone-voice'
      fullPath: '/api/clone-voice'
      preLoaderRoute: typeof ApiCloneVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-generations': {
      id: '/api/public/expire-generations'
      path: '/api/public/expire-generations'
      fullPath: '/api/public/expire-generations'
      preLoaderRoute: typeof ApiPublicExpireGenerationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjustesRoute: AjustesRoute,
  AppRoute: AppRoute,
  ContaRoute: ContaRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiCloneVoiceRoute: ApiCloneVoiceRoute,
  ApiConfirmVoiceRoute: ApiConfirmVoiceRoute,
  ApiDeleteVoiceRoute: ApiDeleteVoiceRoute,
  ApiFalStatusRoute: ApiFalStatusRoute,
  ApiGenerateCaptionRoute: ApiGenerateCaptionRoute,
  ApiGenerateContentRoute: ApiGenerateContentRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGeneratePuCopyRoute: ApiGeneratePuCopyRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiRegenerateBlockRoute: ApiRegenerateBlockRoute,
  ApiSuggestKeyinfoRoute: ApiSuggestKeyinfoRoute,
  ApiSupabasePdfRoute: ApiSupabasePdfRoute,
  ApiTtsVoiceRoute: ApiTtsVoiceRoute,
  ApiPublicExpireGenerationsRoute: ApiPublicExpireGenerationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
