// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Response('Unauthorized: No request headers available', { status: 401 });
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Response('Unauthorized: No authorization header provided', { status: 401 });
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Response('Unauthorized: Only Bearer tokens are supported', { status: 401 });
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Response('Unauthorized: No token provided', { status: 401 });
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    let userId: string;
    let claims: Record<string, unknown>;

    // Try getClaims (validates signature via JWKS). Falls back to local decode
    // if the JWKS network call fails (e.g., corporate SSL proxy after server restart).
    try {
      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims?.sub) throw error || new Error('getClaims failed');
      userId = data.claims.sub as string;
      claims = data.claims as Record<string, unknown>;
    } catch {
      try {
        const parts = token.split('.');
        if (parts.length !== 3) throw new Error('bad jwt');
        const padded = parts[1].replace(/-/g, '+').replace(/_/g, '/');
        const payload = JSON.parse(Buffer.from(padded, 'base64').toString('utf8'));
        if (!payload?.sub) throw new Error('no sub');
        if (payload.exp && payload.exp < Math.floor(Date.now() / 1000))
          throw new Response('Unauthorized: Token expired', { status: 401 });
        userId = payload.sub as string;
        claims = payload as Record<string, unknown>;
      } catch (e) {
        if (e instanceof Response) throw e;
        throw new Response('Unauthorized: Invalid token', { status: 401 });
      }
    }

    return next({
      context: {
        supabase,
        userId,
        claims,
      },
    })
  }
)
